"""Financing router — CRUD for instruments, obligations, payments, and dashboard."""

import math
from datetime import date, datetime, timedelta
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import func
from sqlalchemy.orm import Session

from core.financing.amortization import calculate_amortization_schedule
from core.financing.obligation_engine import _add_months, generate_obligations
from core.financing.wrap_calculator import calculate_wrap_spread
from core.security.jwt import get_current_user
from core.telemetry import track_event
from database import get_db
from models.financing_instruments import FinancingInstrument
from models.obligations import Obligation
from models.payments import Payment
from models.properties import Property
from models.users import User
from schemas.financing import (
    AmortizationEntry,
    BalloonAlert,
    CreateFinancingInstrumentRequest,
    CreatePaymentRequest,
    DueOnSaleRiskItem,
    FinancingDashboardResponse,
    FinancingInstrumentResponse,
    InstrumentDetailResponse,
    InstrumentListItem,
    MonthlyHistory,
    ObligationCompleteRequest,
    ObligationGrouped,
    ObligationResponse,
    ObligationWithComputed,
    PaginatedInstruments,
    PaginatedObligations,
    PaginatedPayments,
    PaymentResponse,
    PaymentSummaryResponse,
    PropertyPaymentSummary,
    UpdateFinancingInstrumentRequest,
    UpdateObligationRequest,
    WrapSpreadItem,
    WrapSpreadSummary,
)

router = APIRouter(prefix="/financing", tags=["financing"])

# Fields that trigger obligation regeneration when changed
_TERM_FIELDS = {
    "interest_rate", "monthly_payment", "term_months", "amortization_months",
    "first_payment_date", "maturity_date", "has_balloon", "balloon_date",
    "balloon_amount", "requires_insurance", "insurance_verified_date",
    "rate_type", "instrument_type", "option_expiration", "strike_price",
    "wrap_rate", "wrap_payment",
}

# Obligation types generated by the engine (vs. manually created)
_AUTO_OBLIGATION_TYPES = {
    "monthly_payment", "balloon_payment", "insurance_renewal",
    "option_expiration", "rate_adjustment",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_instrument_or_404(
    db: Session, instrument_id: UUID, user_id: UUID,
) -> FinancingInstrument:
    inst = (
        db.query(FinancingInstrument)
        .filter(
            FinancingInstrument.id == instrument_id,
            FinancingInstrument.created_by == user_id,
            FinancingInstrument.deleted_at.is_(None),
        )
        .first()
    )
    if not inst:
        raise HTTPException(
            status_code=404,
            detail={"error": "Instrument not found", "code": "INSTRUMENT_NOT_FOUND"},
        )
    return inst


def _get_obligation_or_404(
    db: Session, obligation_id: UUID, user_id: UUID,
) -> Obligation:
    obl = (
        db.query(Obligation)
        .filter(
            Obligation.id == obligation_id,
            Obligation.created_by == user_id,
            Obligation.deleted_at.is_(None),
        )
        .first()
    )
    if not obl:
        raise HTTPException(
            status_code=404,
            detail={"error": "Obligation not found", "code": "OBLIGATION_NOT_FOUND"},
        )
    return obl


def _validate_property_ownership(db: Session, property_id: UUID, user_id: UUID) -> Property:
    prop = (
        db.query(Property)
        .filter(
            Property.id == property_id,
            Property.created_by == user_id,
            Property.is_deleted == False,  # noqa: E712
        )
        .first()
    )
    if not prop:
        raise HTTPException(
            status_code=404,
            detail={"error": "Property not found", "code": "PROPERTY_NOT_FOUND"},
        )
    return prop


def _compute_instrument_extras(
    instrument: FinancingInstrument, db: Session,
) -> dict:
    """Compute derived fields for an instrument."""
    extras: dict = {
        "months_remaining": None,
        "next_payment_due": None,
        "payoff_amount_estimate": None,
        "wrap_spread": None,
    }

    # Months remaining
    if instrument.maturity_date:
        delta = (instrument.maturity_date - date.today()).days
        extras["months_remaining"] = max(delta // 30, 0)

    # Next payment due — from first active monthly obligation
    monthly_obl = (
        db.query(Obligation)
        .filter(
            Obligation.instrument_id == instrument.id,
            Obligation.obligation_type == "monthly_payment",
            Obligation.status == "active",
            Obligation.deleted_at.is_(None),
        )
        .first()
    )
    if monthly_obl and monthly_obl.next_due:
        extras["next_payment_due"] = monthly_obl.next_due

    # Payoff estimate
    if instrument.current_balance is not None:
        extras["payoff_amount_estimate"] = float(instrument.current_balance)

    # Wrap spread
    if instrument.is_wrap and instrument.underlying_instrument_id:
        underlying = (
            db.query(FinancingInstrument)
            .filter(
                FinancingInstrument.id == instrument.underlying_instrument_id,
                FinancingInstrument.created_by == instrument.created_by,
                FinancingInstrument.deleted_at.is_(None),
            )
            .first()
        )
        if underlying:
            spread = calculate_wrap_spread(instrument, underlying)
            extras["wrap_spread"] = WrapSpreadSummary(**spread)

    return extras


def _build_obligation_computed(
    obl: Obligation, instrument_name: str = "", property_address: str = "",
) -> dict:
    """Build computed fields for an obligation."""
    days = None
    is_overdue = False
    if obl.next_due:
        days = (obl.next_due - date.today()).days
        if days < 0 and obl.status == "active":
            is_overdue = True
    return {
        "days_until_due": days,
        "is_overdue": is_overdue,
        "instrument_name": instrument_name,
        "property_address": property_address,
    }


def _estimate_pi_split(instrument: FinancingInstrument, amount: float) -> tuple[float, float]:
    """Estimate principal and interest portions from instrument terms.
    Returns (principal, interest). If rate is 0 or null, all principal."""
    rate = float(instrument.interest_rate or 0)
    balance = float(instrument.current_balance or 0)
    if rate <= 0 or balance <= 0:
        return (amount, 0.0)
    monthly_rate = rate / 100 / 12
    interest = balance * monthly_rate
    principal = amount - interest
    if principal < 0:
        principal = 0.0
        interest = amount
    return (round(principal, 2), round(interest, 2))


def _update_balance_from_payment(
    instrument: FinancingInstrument,
    amount: float,
    principal_portion: float | None,
    interest_portion: float | None,
) -> tuple[float, float]:
    """Update instrument balance and return (principal, interest) used.

    If principal_portion is provided, use it directly.
    Otherwise estimate from instrument terms.
    Balance is clamped to 0 (never goes negative).
    If balance reaches 0, instrument is marked paid_off.
    """
    if instrument.current_balance is None:
        return (0.0, 0.0)

    if principal_portion is not None:
        principal = float(principal_portion)
        interest = float(interest_portion or 0)
    else:
        principal, interest = _estimate_pi_split(instrument, amount)

    new_balance = max(float(instrument.current_balance) - principal, 0)
    instrument.current_balance = new_balance

    # Auto mark paid off
    if new_balance == 0 and instrument.status == "active":
        instrument.status = "paid_off"

    return (principal, interest)


# ---------------------------------------------------------------------------
# Instruments
# ---------------------------------------------------------------------------

@router.get("/instruments", response_model=PaginatedInstruments)
async def list_instruments(
    property_id: Optional[UUID] = Query(None),
    instrument_status: Optional[str] = Query(None, alias="status"),
    instrument_type: Optional[str] = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    q = db.query(FinancingInstrument).filter(
        FinancingInstrument.created_by == current_user.id,
        FinancingInstrument.deleted_at.is_(None),
    )
    if property_id:
        q = q.filter(FinancingInstrument.property_id == property_id)
    if instrument_status:
        q = q.filter(FinancingInstrument.status == instrument_status)
    if instrument_type:
        q = q.filter(FinancingInstrument.instrument_type == instrument_type)

    total = q.count()

    instruments = (
        q.join(Property, Property.id == FinancingInstrument.property_id)
        .order_by(Property.address_line1, FinancingInstrument.position)
        .offset((page - 1) * per_page)
        .limit(per_page)
        .all()
    )

    items = []
    for inst in instruments:
        extras = _compute_instrument_extras(inst, db)
        item = InstrumentListItem.model_validate(inst, from_attributes=True)
        for k, v in extras.items():
            setattr(item, k, v)
        items.append(item)

    return PaginatedInstruments(
        items=items,
        total=total,
        page=page,
        per_page=per_page,
        pages=math.ceil(total / per_page) if total else 0,
    )


@router.get("/instruments/{instrument_id}", response_model=InstrumentDetailResponse)
async def get_instrument(
    instrument_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    inst = _get_instrument_or_404(db, instrument_id, current_user.id)

    # Active obligations
    obligations = (
        db.query(Obligation)
        .filter(
            Obligation.instrument_id == inst.id,
            Obligation.deleted_at.is_(None),
        )
        .order_by(Obligation.next_due.asc().nullslast())
        .all()
    )

    # Last 5 payments
    recent_payments = (
        db.query(Payment)
        .filter(
            Payment.instrument_id == inst.id,
            Payment.deleted_at.is_(None),
        )
        .order_by(Payment.payment_date.desc())
        .limit(5)
        .all()
    )

    # Wrap spread
    wrap_spread = None
    if inst.is_wrap and inst.underlying_instrument_id:
        underlying = (
            db.query(FinancingInstrument)
            .filter(
                FinancingInstrument.id == inst.underlying_instrument_id,
                FinancingInstrument.created_by == current_user.id,
                FinancingInstrument.deleted_at.is_(None),
            )
            .first()
        )
        if underlying:
            spread = calculate_wrap_spread(inst, underlying)
            wrap_spread = WrapSpreadSummary(**spread)

    # Amortization schedule
    amortization = []
    if inst.current_balance and inst.interest_rate and inst.monthly_payment:
        amortization = calculate_amortization_schedule(
            balance=float(inst.current_balance),
            annual_rate=float(inst.interest_rate),
            monthly_payment=float(inst.monthly_payment),
            months=12,
            start_date=date.today(),
        )

    resp = InstrumentDetailResponse.model_validate(inst, from_attributes=True)
    resp.obligations = [ObligationResponse.model_validate(o, from_attributes=True) for o in obligations]
    resp.recent_payments = [PaymentResponse.model_validate(p, from_attributes=True) for p in recent_payments]
    resp.wrap_spread = wrap_spread
    resp.amortization_schedule = [AmortizationEntry(**e) for e in amortization]
    return resp


@router.post(
    "/instruments",
    response_model=FinancingInstrumentResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_instrument(
    body: CreateFinancingInstrumentRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    _validate_property_ownership(db, body.property_id, current_user.id)

    # Validate wrap underlying
    if body.instrument_type == "wrap_mortgage" and body.underlying_instrument_id:
        underlying = _get_instrument_or_404(db, body.underlying_instrument_id, current_user.id)
        if underlying.property_id != body.property_id:
            raise HTTPException(
                status_code=400,
                detail={
                    "error": "Underlying instrument must belong to the same property",
                    "code": "INSTRUMENT_PROPERTY_MISMATCH",
                },
            )

    # Auto-set due_on_sale_risk for sub-to
    data = body.model_dump()
    if body.instrument_type == "sub_to_mortgage" and not body.due_on_sale_risk:
        risk_map = {"conventional": "high", "fha": "low", "va": "low", "portfolio": "medium"}
        loan_type = (data.get("rate_type") or "").lower()
        data["due_on_sale_risk"] = risk_map.get(loan_type, "high")

    instrument = FinancingInstrument(
        **data,
        created_by=current_user.id,
        team_id=current_user.team_id,
    )
    db.add(instrument)
    db.flush()

    # Generate obligations
    obligations = generate_obligations(instrument)
    for obl in obligations:
        obl.created_by = current_user.id
        obl.team_id = current_user.team_id
    db.add_all(obligations)
    db.commit()
    db.refresh(instrument)

    try:
        track_event(current_user.id, "instrument_created", {
            "instrument_type": instrument.instrument_type,
            "has_balloon": instrument.has_balloon,
            "is_wrap": instrument.is_wrap,
            "is_sub_to": instrument.is_sub_to,
        })
    except Exception:
        pass

    return FinancingInstrumentResponse.model_validate(instrument, from_attributes=True)


@router.patch("/instruments/{instrument_id}", response_model=FinancingInstrumentResponse)
async def update_instrument(
    instrument_id: UUID,
    body: UpdateFinancingInstrumentRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    inst = _get_instrument_or_404(db, instrument_id, current_user.id)
    update_data = body.model_dump(exclude_unset=True)

    # Validate underlying_instrument_id on update
    new_underlying = update_data.get("underlying_instrument_id")
    if new_underlying is not None:
        # No self-reference
        if str(new_underlying) == str(instrument_id):
            raise HTTPException(status_code=400, detail={
                "error": "Instrument cannot reference itself",
                "code": "SELF_REFERENCE",
            })
        # Must belong to same user and same property
        underlying = _get_instrument_or_404(db, new_underlying, current_user.id)
        if underlying.property_id != inst.property_id:
            raise HTTPException(status_code=400, detail={
                "error": "Underlying instrument must belong to the same property",
                "code": "INSTRUMENT_PROPERTY_MISMATCH",
            })
        # Check for circular reference
        seen = {str(instrument_id)}
        current = underlying
        while current.underlying_instrument_id:
            uid = str(current.underlying_instrument_id)
            if uid in seen:
                raise HTTPException(status_code=400, detail={
                    "error": "Circular instrument reference detected",
                    "code": "CIRCULAR_REFERENCE",
                })
            seen.add(uid)
            current = db.query(FinancingInstrument).filter(
                FinancingInstrument.id == current.underlying_instrument_id,
                FinancingInstrument.deleted_at.is_(None),
            ).first()
            if not current:
                break

    for key, value in update_data.items():
        setattr(inst, key, value)

    # Regenerate obligations if terms changed
    if update_data.keys() & _TERM_FIELDS:
        now = datetime.utcnow()
        db.query(Obligation).filter(
            Obligation.instrument_id == inst.id,
            Obligation.deleted_at.is_(None),
            Obligation.obligation_type.in_(_AUTO_OBLIGATION_TYPES),
        ).update({"deleted_at": now}, synchronize_session="fetch")

        new_obligations = generate_obligations(inst)
        for obl in new_obligations:
            obl.created_by = current_user.id
            obl.team_id = current_user.team_id
        db.add_all(new_obligations)

    db.commit()
    db.refresh(inst)

    try:
        track_event(current_user.id, "instrument_updated", {
            "instrument_id": str(instrument_id),
            "fields_changed": list(update_data.keys()),
        })
    except Exception:
        pass

    return FinancingInstrumentResponse.model_validate(inst, from_attributes=True)


@router.delete(
    "/instruments/{instrument_id}",
    status_code=status.HTTP_204_NO_CONTENT,
)
async def delete_instrument(
    instrument_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    inst = _get_instrument_or_404(db, instrument_id, current_user.id)
    now = datetime.utcnow()
    inst.deleted_at = now

    db.query(Obligation).filter(
        Obligation.instrument_id == inst.id,
        Obligation.deleted_at.is_(None),
    ).update({"deleted_at": now}, synchronize_session="fetch")

    db.query(Payment).filter(
        Payment.instrument_id == inst.id,
        Payment.deleted_at.is_(None),
    ).update({"deleted_at": now}, synchronize_session="fetch")

    db.commit()

    try:
        track_event(current_user.id, "instrument_deleted", {
            "instrument_id": str(instrument_id),
        })
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Obligations
# ---------------------------------------------------------------------------

@router.get("/obligations", response_model=PaginatedObligations)
async def list_obligations(
    instrument_id: Optional[UUID] = Query(None),
    property_id: Optional[UUID] = Query(None),
    obligation_status: Optional[str] = Query(None, alias="status"),
    severity: Optional[str] = Query(None),
    due_before: Optional[date] = Query(None),
    due_after: Optional[date] = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    # Resurface snoozed obligations whose snooze date has passed
    db.query(Obligation).filter(
        Obligation.created_by == current_user.id,
        Obligation.deleted_at.is_(None),
        Obligation.status == "snoozed",
        Obligation.next_due <= date.today(),
    ).update({"status": "active"}, synchronize_session="fetch")

    q = db.query(Obligation).filter(
        Obligation.created_by == current_user.id,
        Obligation.deleted_at.is_(None),
    )
    if instrument_id:
        q = q.filter(Obligation.instrument_id == instrument_id)
    if property_id:
        q = q.filter(Obligation.property_id == property_id)
    if obligation_status:
        q = q.filter(Obligation.status == obligation_status)
    if severity:
        q = q.filter(Obligation.severity == severity)
    if due_before:
        q = q.filter(Obligation.next_due <= due_before)
    if due_after:
        q = q.filter(Obligation.next_due >= due_after)

    total = q.count()

    obligations = (
        q.order_by(Obligation.next_due.asc().nullslast())
        .offset((page - 1) * per_page)
        .limit(per_page)
        .all()
    )

    items = []
    for obl in obligations:
        inst = db.query(FinancingInstrument).get(obl.instrument_id)
        prop = db.query(Property).get(obl.property_id)
        inst_name = inst.name if inst else ""
        prop_addr = prop.address_line1 if prop else ""
        computed = _build_obligation_computed(obl, inst_name, prop_addr)
        item = ObligationWithComputed.model_validate(obl, from_attributes=True)
        for k, v in computed.items():
            setattr(item, k, v)
        items.append(item)

    return PaginatedObligations(
        items=items,
        total=total,
        page=page,
        per_page=per_page,
        pages=math.ceil(total / per_page) if total else 0,
    )


@router.get("/obligations/upcoming", response_model=ObligationGrouped)
async def upcoming_obligations(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    # Resurface snoozed obligations whose snooze date has passed
    db.query(Obligation).filter(
        Obligation.created_by == current_user.id,
        Obligation.deleted_at.is_(None),
        Obligation.status == "snoozed",
        Obligation.next_due <= date.today(),
    ).update({"status": "active"}, synchronize_session="fetch")

    cutoff = date.today() + timedelta(days=90)
    obligations = (
        db.query(Obligation)
        .filter(
            Obligation.created_by == current_user.id,
            Obligation.deleted_at.is_(None),
            Obligation.status == "active",
            Obligation.next_due <= cutoff,
            Obligation.next_due.isnot(None),
        )
        .order_by(Obligation.next_due.asc())
        .all()
    )

    grouped = ObligationGrouped()
    for obl in obligations:
        inst = db.query(FinancingInstrument).get(obl.instrument_id)
        prop = db.query(Property).get(obl.property_id)
        inst_name = inst.name if inst else ""
        prop_addr = prop.address_line1 if prop else ""
        computed = _build_obligation_computed(obl, inst_name, prop_addr)
        item = ObligationWithComputed.model_validate(obl, from_attributes=True)
        for k, v in computed.items():
            setattr(item, k, v)

        if obl.severity == "critical":
            grouped.critical.append(item)
        elif obl.severity == "high":
            grouped.high.append(item)
        else:
            grouped.normal.append(item)

    try:
        track_event(current_user.id, "obligation_briefing_generated", {
            "count": len(obligations),
            "critical_count": len(grouped.critical),
        })
    except Exception:
        pass

    return grouped


@router.patch("/obligations/{obligation_id}", response_model=ObligationResponse)
async def update_obligation(
    obligation_id: UUID,
    body: UpdateObligationRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    obl = _get_obligation_or_404(db, obligation_id, current_user.id)
    update_data = body.model_dump(exclude_unset=True)

    for key, value in update_data.items():
        setattr(obl, key, value)

    # If snoozed, next_due should already be set via the body
    if update_data.get("status") == "completed":
        obl.completed_at = datetime.utcnow() if hasattr(obl, "completed_at") else None

    db.commit()
    db.refresh(obl)
    return ObligationResponse.model_validate(obl, from_attributes=True)


@router.post("/obligations/{obligation_id}/complete", response_model=ObligationResponse)
async def complete_obligation(
    obligation_id: UUID,
    body: ObligationCompleteRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    obl = _get_obligation_or_404(db, obligation_id, current_user.id)

    was_overdue = False
    days_delta = 0
    if obl.next_due:
        days_delta = (date.today() - obl.next_due).days
        was_overdue = days_delta > 0

    # Create payment if details provided
    if body.payment_amount is not None:
        inst = db.query(FinancingInstrument).get(obl.instrument_id)
        principal, interest = _update_balance_from_payment(
            inst, float(body.payment_amount), None, None
        ) if inst else (0.0, 0.0)
        payment = Payment(
            instrument_id=obl.instrument_id,
            obligation_id=obl.id,
            property_id=obl.property_id,
            created_by=current_user.id,
            team_id=current_user.team_id,
            payment_type="regular",
            amount=body.payment_amount,
            principal_portion=principal,
            interest_portion=interest,
            payment_date=body.payment_date or date.today(),
            payment_method=body.payment_method,
            direction="outgoing",
        )
        db.add(payment)

    # Advance recurring obligations or complete one-time
    if obl.recurrence and obl.recurrence != "one_time" and obl.next_due:
        months = {"monthly": 1, "quarterly": 3, "annually": 12}.get(obl.recurrence, 1)
        obl.next_due = _add_months(obl.next_due, months)
        obl.status = "active"
    else:
        obl.status = "completed"

    db.commit()
    db.refresh(obl)

    try:
        track_event(current_user.id, "obligation_completed", {
            "obligation_type": obl.obligation_type,
            "was_overdue": was_overdue,
            "days_early_or_late": days_delta,
        })
    except Exception:
        pass

    return ObligationResponse.model_validate(obl, from_attributes=True)


# ---------------------------------------------------------------------------
# Payments
# ---------------------------------------------------------------------------

@router.get("/payments", response_model=PaginatedPayments)
async def list_payments(
    instrument_id: Optional[UUID] = Query(None),
    property_id: Optional[UUID] = Query(None),
    direction: Optional[str] = Query(None),
    date_from: Optional[date] = Query(None),
    date_to: Optional[date] = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    q = db.query(Payment).filter(
        Payment.created_by == current_user.id,
        Payment.deleted_at.is_(None),
    )
    if instrument_id:
        q = q.filter(Payment.instrument_id == instrument_id)
    if property_id:
        q = q.filter(Payment.property_id == property_id)
    if direction:
        q = q.filter(Payment.direction == direction)
    if date_from:
        q = q.filter(Payment.payment_date >= date_from)
    if date_to:
        q = q.filter(Payment.payment_date <= date_to)

    total = q.count()

    payments = (
        q.order_by(Payment.payment_date.desc())
        .offset((page - 1) * per_page)
        .limit(per_page)
        .all()
    )

    return PaginatedPayments(
        items=[PaymentResponse.model_validate(p, from_attributes=True) for p in payments],
        total=total,
        page=page,
        per_page=per_page,
        pages=math.ceil(total / per_page) if total else 0,
    )


@router.post(
    "/payments",
    response_model=PaymentResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_payment(
    body: CreatePaymentRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    # Validate instrument ownership
    inst = _get_instrument_or_404(db, body.instrument_id, current_user.id)

    # Validate obligation belongs to instrument and user
    if body.obligation_id:
        obl_check = db.query(Obligation).filter(
            Obligation.id == body.obligation_id,
            Obligation.instrument_id == body.instrument_id,
            Obligation.created_by == current_user.id,
            Obligation.deleted_at.is_(None),
        ).first()
        if not obl_check:
            raise HTTPException(status_code=400, detail={
                "error": "Obligation not found or does not belong to this instrument",
                "code": "OBLIGATION_MISMATCH",
            })

    # Estimate P&I if not provided
    principal = body.principal_portion
    interest = body.interest_portion
    if principal is None and body.amount:
        est_p, est_i = _estimate_pi_split(inst, float(body.amount))
        principal = est_p
        interest = est_i

    _update_balance_from_payment(
        inst, float(body.amount),
        float(principal) if principal is not None else None,
        float(interest) if interest is not None else None,
    )

    payment_data = body.model_dump()
    payment_data['principal_portion'] = principal
    payment_data['interest_portion'] = interest
    payment_data['property_id'] = inst.property_id  # S1: derive from instrument
    payment = Payment(
        **payment_data,
        created_by=current_user.id,
        team_id=current_user.team_id,
    )
    db.add(payment)

    # Advance obligation if linked
    if body.obligation_id:
        obl = (
            db.query(Obligation)
            .filter(
                Obligation.id == body.obligation_id,
                Obligation.created_by == current_user.id,
                Obligation.deleted_at.is_(None),
            )
            .first()
        )
        if obl and obl.recurrence and obl.recurrence != "one_time" and obl.next_due:
            months = {"monthly": 1, "quarterly": 3, "annually": 12}.get(obl.recurrence, 1)
            obl.next_due = _add_months(obl.next_due, months)

    db.commit()
    db.refresh(payment)

    try:
        track_event(current_user.id, "payment_recorded", {
            "direction": body.direction,
            "amount": float(body.amount),
            "instrument_type": inst.instrument_type,
        })
    except Exception:
        pass

    return PaymentResponse.model_validate(payment, from_attributes=True)


@router.get("/payments/summary", response_model=PaymentSummaryResponse)
async def payment_summary(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    twelve_months_ago = date.today() - timedelta(days=365)

    payments = (
        db.query(Payment)
        .filter(
            Payment.created_by == current_user.id,
            Payment.deleted_at.is_(None),
            Payment.payment_date >= twelve_months_ago,
        )
        .all()
    )

    total_outgoing = 0.0
    total_incoming = 0.0
    outgoing_by_prop: dict[UUID, float] = {}
    incoming_by_prop: dict[UUID, float] = {}
    monthly_buckets: dict[str, dict] = {}

    for p in payments:
        amt = float(p.amount or 0)
        month_key = p.payment_date.strftime("%Y-%m")

        if month_key not in monthly_buckets:
            monthly_buckets[month_key] = {"incoming": 0.0, "outgoing": 0.0}

        if p.direction == "outgoing":
            total_outgoing += amt
            outgoing_by_prop[p.property_id] = outgoing_by_prop.get(p.property_id, 0) + amt
            monthly_buckets[month_key]["outgoing"] += amt
        else:
            total_incoming += amt
            incoming_by_prop[p.property_id] = incoming_by_prop.get(p.property_id, 0) + amt
            monthly_buckets[month_key]["incoming"] += amt

    # Resolve property addresses
    prop_ids = set(outgoing_by_prop.keys()) | set(incoming_by_prop.keys())
    props = {}
    if prop_ids:
        for prop in db.query(Property).filter(Property.id.in_(prop_ids)).all():
            props[prop.id] = prop.address_line1 or str(prop.id)

    months_count = max(len(monthly_buckets), 1)

    outgoing_list = [
        PropertyPaymentSummary(
            property_id=pid,
            address=props.get(pid, str(pid)),
            total=round(total, 2),
        )
        for pid, total in outgoing_by_prop.items()
    ]
    incoming_list = [
        PropertyPaymentSummary(
            property_id=pid,
            address=props.get(pid, str(pid)),
            total=round(total, 2),
        )
        for pid, total in incoming_by_prop.items()
    ]

    history = sorted([
        MonthlyHistory(
            month=k,
            incoming=round(v["incoming"], 2),
            outgoing=round(v["outgoing"], 2),
            net=round(v["incoming"] - v["outgoing"], 2),
        )
        for k, v in monthly_buckets.items()
    ], key=lambda h: h.month)

    return PaymentSummaryResponse(
        total_outgoing_monthly=round(total_outgoing / months_count, 2),
        total_incoming_monthly=round(total_incoming / months_count, 2),
        net_monthly=round((total_incoming - total_outgoing) / months_count, 2),
        outgoing_by_property=outgoing_list,
        incoming_by_property=incoming_list,
        payment_history=history,
    )


# ---------------------------------------------------------------------------
# Dashboard
# ---------------------------------------------------------------------------

@router.get("/dashboard", response_model=FinancingDashboardResponse)
async def financing_dashboard(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    instruments = (
        db.query(FinancingInstrument)
        .filter(
            FinancingInstrument.created_by == current_user.id,
            FinancingInstrument.deleted_at.is_(None),
            FinancingInstrument.status == "active",
        )
        .all()
    )

    total_balance = sum(float(i.current_balance or 0) for i in instruments)
    total_monthly_obligations = sum(
        float(i.monthly_payment or 0) for i in instruments if not i.is_wrap
    )
    total_monthly_income = sum(
        float(i.wrap_payment or 0) for i in instruments if i.is_wrap
    )

    # Upcoming balloons (next 3)
    balloon_obls = (
        db.query(Obligation)
        .filter(
            Obligation.created_by == current_user.id,
            Obligation.deleted_at.is_(None),
            Obligation.obligation_type == "balloon_payment",
            Obligation.status == "active",
            Obligation.next_due.isnot(None),
        )
        .order_by(Obligation.next_due.asc())
        .limit(3)
        .all()
    )
    upcoming_balloons = []
    for bobl in balloon_obls:
        inst = db.query(FinancingInstrument).get(bobl.instrument_id)
        prop = db.query(Property).get(bobl.property_id)
        upcoming_balloons.append(BalloonAlert(
            instrument_name=inst.name if inst else "",
            property_address=prop.address_line1 if prop else "",
            balloon_date=bobl.next_due,
            balloon_amount=bobl.amount,
            days_until=(bobl.next_due - date.today()).days if bobl.next_due else None,
        ))

    # Wrap spreads
    wrap_spreads = []
    for inst in instruments:
        if inst.is_wrap and inst.underlying_instrument_id:
            underlying = (
                db.query(FinancingInstrument)
                .filter(
                    FinancingInstrument.id == inst.underlying_instrument_id,
                    FinancingInstrument.created_by == current_user.id,
                    FinancingInstrument.deleted_at.is_(None),
                )
                .first()
            )
            if underlying:
                spread = calculate_wrap_spread(inst, underlying)
                prop = db.query(Property).get(inst.property_id)
                wrap_spreads.append(WrapSpreadItem(
                    property_address=prop.address_line1 if prop else "",
                    monthly_spread=spread["monthly_spread"],
                    annual_spread=spread["annual_spread"],
                ))

    # Due-on-sale risks
    due_on_sale_risks = []
    for inst in instruments:
        if inst.is_sub_to and inst.due_on_sale_risk:
            prop = db.query(Property).get(inst.property_id)
            due_on_sale_risks.append(DueOnSaleRiskItem(
                property_address=prop.address_line1 if prop else "",
                instrument_name=inst.name,
                risk_level=inst.due_on_sale_risk,
            ))

    try:
        track_event(current_user.id, "financing_dashboard_viewed", {
            "total_instruments": len(instruments),
            "has_wraps": any(i.is_wrap for i in instruments),
            "has_sub_to": any(i.is_sub_to for i in instruments),
        })
    except Exception:
        pass

    return FinancingDashboardResponse(
        total_instruments=len(instruments),
        total_balance=round(total_balance, 2),
        total_monthly_obligations=round(total_monthly_obligations, 2),
        total_monthly_income=round(total_monthly_income, 2),
        net_monthly_cash_flow=round(total_monthly_income - total_monthly_obligations, 2),
        upcoming_balloons=upcoming_balloons,
        wrap_spreads=wrap_spreads,
        due_on_sale_risks=due_on_sale_risks,
    )
