/** Simple PDF Document for offer letter download. */

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer'
import { registerPDFFonts } from '@/lib/pdf-fonts'

registerPDFFonts()

const s = StyleSheet.create({
  page: {
    backgroundColor: '#08080F',
    padding: 48,
    fontFamily: 'Inter',
    color: '#F1F5F9',
    fontSize: 11,
  },
  header: {
    marginBottom: 24,
    borderBottom: '1 solid #1A1A2E',
    paddingBottom: 16,
  },
  wordmark: {
    fontFamily: 'JetBrains Mono',
    fontWeight: 700,
    fontSize: 20,
    color: '#6366F1',
    letterSpacing: 3,
  },
  subtitle: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 4,
  },
  address: {
    fontSize: 14,
    fontWeight: 700,
    color: '#F1F5F9',
    marginTop: 4,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.7,
    color: '#E2E8F0',
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 48,
    right: 48,
    borderTop: '1 solid #1A1A2E',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 8,
    color: '#64748B',
  },
})

interface OfferLetterPDFProps {
  address: string
  letterText: string
  generatedAt: string
}

export function OfferLetterPDF({ address, letterText, generatedAt }: OfferLetterPDFProps) {
  const dateFormatted = new Date(generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.wordmark}>PARCEL</Text>
          <Text style={s.subtitle}>Offer Letter</Text>
          <Text style={s.address}>{address}</Text>
        </View>

        <Text style={s.body}>{letterText}</Text>

        <View style={s.footer} fixed>
          <Text style={s.footerText}>
            Generated by Parcel &middot; {dateFormatted}
          </Text>
          <Text
            style={s.footerText}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  )
}
